### ISSUE TITLE
AGP8.0 Transform遭移除

### ISSUE THREAD

**Issue by xzzvsxd** [wuzuchang/StringObfuscatedPlugin#2]
* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin 'com.wzc.string.obfuscate'.
   > API 'android.registerTransform' is removed.
     
     For more information, see https://developer.android.com/studio/releases/gradle-plugin-api-updates#transform-api.
     To determine what is calling android.registerTransform, use -Pandroid.debug.obsoleteApi=true on the command line to display more information.

**Comment by wuzuchang** [comment]
我有空的话，升级一下

**Comment by wuzuchang** [comment]
更新了
