### ISSUE TITLE
无法导入插件

### ISSUE THREAD

**Issue by xzzvsxd** [wuzuchang/StringObfuscatedPlugin#3]
> Could not resolve all files for configuration ':classpath'.
   > Could not find com.github.wuzuchang.StringObfuscatedPlugin:string_obfuscated:2.0.0.
     Searched in the following locations:
       - https://maven.aliyun.com/nexus/content/groups/public/com/github/wuzuchang/StringObfuscatedPlugin/string_obfuscated/2.0.0/string_obfuscated-2.0.0.pom
       - https://maven.aliyun.com/repository/public/com/github/wuzuchang/StringObfuscatedPlugin/string_obfuscated/2.0.0/string_obfuscated-2.0.0.pom
       - https://maven.aliyun.com/repository/google/com/github/wuzuchang/StringObfuscatedPlugin/string_obfuscated/2.0.0/string_obfuscated-2.0.0.pom
       - https://maven.aliyun.com/repository/jcenter/com/github/wuzuchang/StringObfuscatedPlugin/string_obfuscated/2.0.0/string_obfuscated-2.0.0.pom
       - https://maven.aliyun.com/repository/central/com/github/wuzuchang/StringObfuscatedPlugin/string_obfuscated/2.0.0/string_obfuscated-2.0.0.pom
       - https://jitpack.io/com/github/wuzuchang/StringObfuscatedPlugin/string_obfuscated/2.0.0/string_obfuscated-2.0.0.pom
       - file:/C:/Users/Administrator/.m2/repository/com/github/wuzuchang/StringObfuscatedPlugin/string_obfuscated/2.0.0/string_obfuscated-2.0.0.pom
       - https://repo.maven.apache.org/maven2/com/github/wuzuchang/StringObfuscatedPlugin/string_obfuscated/2.0.0/string_obfuscated-2.0.0.pom
       - https://dl.google.com/dl/android/maven2/com/github/wuzuchang/StringObfuscatedPlugin/string_obfuscated/2.0.0/string_obfuscated-2.0.0.pom
       - file:/D:/APPProjects/XX/plugin_libs/string_obfuscated-2.0.0.jar
       - file:/D:/APPProjects/XX/plugin_libs/string_obfuscated.jar
     Required by:
         project : > com.github.wuzuchang:StringObfuscatedPlugin:2.0.0

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by wuzuchang** [comment]
使用 classpath 'com.github.wuzuchang:StringObfuscatePlugin:2.0.0'，中间不需要加string_obfuscated

**Comment by xzzvsxd** [comment]
就是classpath 'com.github.wuzuchang:StringObfuscatedPlugin:2.0.0' 就是提示这个报错，请您自己测试一下！

**Comment by wuzuchang** [comment]
请使用 classpath 'com.github.wuzuchang:StringObfuscatedPlugin:2.1.0'
